COMPONENT=EasyCollectionAppC
PFLAGS += -I$(TOSDIR)/lib/printf
PFLAGS+=-DRF230_DEF_CHANNEL=26
PFLAGS+=-DCC2420_DEF_CHANNEL=26
CFLAGS += -I$(TOSDIR)/lib/net \
          -I$(TOSDIR)/lib/net/le \
          -I$(TOSDIR)/lib/net/ctp
include $(MAKERULES)